name = "facturation-abby2"
main = "src/index.js"
compatibility_date = "2026-01-01"

# ─── KV NAMESPACE ─────────────────────────────────────────────────────────────
[[kv_namespaces]]
binding = "ORDERS"
id = "5598e401dc1f4e70a882286de3899b3c"

# ─── QUEUE ────────────────────────────────────────────────────────────────────
[[queues.producers]]
binding = "ORDER_QUEUE"
queue = "webhook-orders"

[[queues.consumers]]
queue = "webhook-orders"
max_batch_size = 10
max_batch_timeout = 5

# ─── VARIABLES D'ENVIRONNEMENT ────────────────────────────────────────────────
[vars]
DELAY_SECONDS = "60"

# ─── OBSERVABILITY ────────────────────────────────────────────────────────────
[observability]
enabled = true
